"""Mudança dos nomes dos atributos das entidades

Revision ID: 0a0a73f81506
Revises: 3836da54ea2d
Create Date: 2024-05-18 18:08:36.556252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0a73f81506'
down_revision: Union[str, None] = '3836da54ea2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
